baseurl = "https://pelicanjoe.com/"
languageCode = "en-us"
title = "A Project"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"


[params]
    site_author = "Joe"
    site_description = "A Hugo Project by Joe"
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "images/github-icon.png"
    header_background = "images/network.jpg"
    header_title = "A Hugo Project by Joe"
    copyright = "Powered by [Hugo](http://gohugo.io) and Joe."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "spf13"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "joetechem"
    gplus     = ""
